---
title: The Philosophers Meme
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: |
  The Philosophers Meme blog.
baseurl: 
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Anonymous"
      image: /assets/img/sample-image.png
      release-type: "guest"
