---
title: The Philosopher's Meme
timezone: Pacific/Auckland
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    type: post
    author:
      login: username
      email: email@wherever.com
      display_name: Author
      first_name: Philosopher
      last_name: Of The Meme
    excerpt: The Philosopher's Meme
    image: "/assets/tpm_defaultpic.jpg"
    banner: "/assets/tpm_defaultpic.jpg"
    fbpreview: http://thephilosophersmeme.com/assets/img/nav/tpm-header.png
    release-type: official
sass:
  style: compressed
email: your-email@domain.com
description: The Philosopher's Meme
baseurl: 
url: http://thephilosophersmeme.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
paginate: 8
gems:
- jemoji
- jekyll-seo-tag
- jekyll-paginate
permalink: "/:year/:month/:day/:title/"
