---
title: The Philosophers Meme
timezone: UTC
sass:
  style: compressed
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
    author: Anonymous
    image: "/assets/img/sample-image.gif"
    banner: "/assets/img/sample-banner.gif"
    release-type: guest
email: your-email@domain.com
description: |
  The Philosophers Meme blog.
baseurl: 
url: http://philosophersmeme.siteleaf.net
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown